### ISSUE TITLE
Investigate to working with jetpack composer from project start

### ISSUE THREAD

**Issue by vmadalin** [urbannoise/urban-noise-mobile-android-app#7]
Read the documentation about [Composer](https://developer.android.com/jetpack/compose), the newest modern toolkit for building native UI.

Things to take into consideration
- MIN SDK Required
- Level of support on Android Studio
- Limitations using Composer over using XML layouts.

**Comment by jmpaya** [comment]
Here I share some of the information I've researched about Jetpack Compose:

- Android Studio **4.1 canary** version required
- Min. Android SDK **21**
- Official testing library [Joe Birch post](https://joebirch.co/android/early-learnings-in-testing-with-jetpack-compose/)

Nice sample projects using Jetpack Compose:
- [Twitter clone](https://github.com/ahmedrizwan/JetpackComposeTwitter)
- [Coffee drinks](https://github.com/AlexZhukovich/CoffeeDrinksWithJetpackCompose)
- [JetNews](https://github.com/android/compose-samples)
- [Pokedex](https://github.com/zsoltk/compose-pokedex)
- [List of tutorials](https://github.com/Foso/Jetpack-Compose-Playground)

_Note: The only drawback I've heard about is that adapters are too slow when using Compose, it's mentioned on the video I attached at the bottom._

Useful links:
- [Droidcon - Become a Composer](https://www.droidcon.com/media-detail?video=412304809)
- [Jetpack Compose Codelab](https://codelabs.developers.google.com/codelabs/jetpack-compose-basics/#1)
- [Joe Birch - ComposeAcademy](https://joebirch.co/android/early-learnings-in-testing-with-jetpack-compose/)

**Comment by jmpaya** [comment]
Take a look to my comment when having a gap @VMadalin, but from my point of view we must give a try to Jetpack Compose, there is a lot of interest over the Internet, so it looks that is going to be the main UI toolkit soon.
